version: "3"
# networks:
#   proxynet:
#     driver: bridge

services:
  db:
    image: postgres:14.1-alpine
    hostname: my_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '54321:5432'
    volumes: 
      - db:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql
    # networks:
    #   - proxynet
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"
  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - db
    volumes:
      - ./server:/app
    environment:
      - PORT=3002
      # NODE_ENV: production
      # DB_HOST: db
      # DB_PORT: 54321
      # DB_USER: postgres
      # DB_PASSWORD: postgres
      # DB_NAME: postgres
    ports:
      - 3002:3002
    links:
      - db  
      
  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
      - PORT=3001
    build:
      dockerfile: Dockerfile
      context: ./client
    depends_on:
      - db
    # depends_on:
    #   - api
    volumes:
      - ./client:/app
    ports:
      - 3001:3001
  
volumes:
  db:
    driver: local
